"""Generate zonehook's symbol table from Zone.pdb.

    python tools/mk_symbols.py --pdb Z:/ServerSource/Zone00/Zone.pdb --exe Z:/ServerSource/Zone00/Zone.exe \
        --out src/zone_symbols.h

Every address the DLL hooks comes from here, never from a number typed into C++. The zone's packet handlers
are `ShinePlayer::sp_NC_<NAME>` - 195 of them - and they are NOT virtual (the mangling says QAE = public
__thiscall, not UAE), so they cannot be reached by swapping a vtable slot; each one is detoured where it
stands. The table also carries the handful of genuinely virtual classes, for the cases where a vtable swap
IS the right tool.

The header is generated, not hand-written, so a different Zone build is one command away rather than a
hunt for stale constants. It records the PDB's own GUID/age so the DLL can refuse to load against an exe it
was not built for.
"""
import argparse
import hashlib
import os
import re
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, 'C:/Projects/Fiesta2026on2016/tools')
import disasm_at as D  # noqa: E402

HANDLER = re.compile(r'^\?(sp_NC_[A-Z0-9_]+)@ShinePlayer@ShineObjectClass@@QAEXPATNETCOMMAND@@HG@Z$')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--pdb', default='Z:/ServerSource/Zone00/Zone.pdb')
    ap.add_argument('--exe', default='Z:/ServerSource/Zone00/Zone.exe')
    ap.add_argument('--out', default=os.path.join(HERE, '..', 'src', 'zone_symbols.h'))
    a = ap.parse_args()

    secs = D.sections(a.exe)[0]   # sections() returns (list, ...); the list is what maps seg -> VA
    pdb = open(a.pdb, 'rb').read()
    base = 0x400000
    handlers, extra = {}, {}
    for name, seg, off in D.publics(pdb):
        if not (1 <= seg <= len(secs)):
            continue
        va = base + secs[seg - 1][0] + off
        m = HANDLER.match(name)
        if m:
            handlers[m.group(1)] = va
        elif name.startswith('??_7') and 'ShinePlayer' in name:
            extra.setdefault(name, va)

    exe_sha = hashlib.sha256(open(a.exe, 'rb').read()).hexdigest()
    out = [
        '// GENERATED by zonehook/tools/mk_symbols.py - do not edit.',
        '//   pdb %s' % os.path.basename(a.pdb),
        '//   exe %s  sha256 %s' % (os.path.basename(a.exe), exe_sha),
        '//',
        '// Addresses are absolute VAs for the default image base 0x%08X. The loader may relocate the image'
        % base,
        '// (the exe sets DYNAMIC_BASE), so every address is rebased at runtime against the real module base:',
        '// see zone::rebase() in hook.h. Never use one of these as a raw pointer.',
        '#pragma once',
        '#include <stdint.h>',
        '',
        'namespace zone {',
        '',
        'static const uint32_t kImageBase = 0x%08Xu;' % base,
        'static const char kExeSha256[] = "%s";' % exe_sha,
        '',
        '// ShinePlayer::sp_NC_<NAME>(TNETCOMMAND*, int, unsigned short) - the packet handlers.',
        '// void __thiscall, so a detour must preserve ECX (the ShinePlayer*).',
        'struct Handler { const char* name; uint32_t va; };',
        'static const Handler kHandlers[] = {',
    ]
    for name in sorted(handlers):
        out.append('    { "%s", 0x%08Xu },' % (name, handlers[name]))
    out += [
        '};',
        'static const int kHandlerCount = %d;' % len(handlers),
        '',
    ]
    if extra:
        out.append('// vtables, for the cases where swapping a slot is the right tool')
        out.append('struct Vtable { const char* name; uint32_t va; };')
        out.append('static const Vtable kVtables[] = {')
        for name in sorted(extra):
            out.append('    { "%s", 0x%08Xu },' % (name.replace('"', ''), extra[name]))
        out += ['};', 'static const int kVtableCount = %d;' % len(extra), '']
    out.append('}  // namespace zone')

    dest = os.path.abspath(a.out)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    open(dest, 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
    print('%s: %d packet handlers, %d vtables' % (dest, len(handlers), len(extra)))


if __name__ == '__main__':
    main()
