// GENERATED by zonehook/tools/mk_char_symbols.py - do not edit, re-run the tool.
//   exe Character.exe  sha256 2889640536a271468ef17cc6c74bd6f8799222e3bd95b81d53ea59d41c5a9e1c
//
// There is no Character.pdb. Handler names come from the log strings each handler writes; framework
// functions are Account.pdb's, found in this exe by their masked bytes. See the tool for both.
// Addresses are VAs at the default base 0x00400000 - rebase at runtime.
#pragma once

namespace chr {

static const unsigned int kImageBase = 0x00400000u;
static const char kExeSha256[] = "2889640536a271468ef17cc6c74bd6f8799222e3bd95b81d53ea59d41c5a9e1c";

// Handlers: int __thiscall CPFs*::fc_NC_*(NETPACKET*, int). Found by their own log string.
struct Handler { const char* name; unsigned int va; };
static const Handler kHandlers[] = {
    { "CGameDB_Character::fc_NC_CHAR_LOGIN_DB", 0x00405810u },
    { "CPFsCharacter::fc_NC_AVATAR_ERASEDATA_REQ", 0x00404CD0u },
    { "CPFsCharacter::fc_NC_AVATAR_GUILD_DATA_REQ", 0x004054F0u },
    { "CPFsCharacter::fc_NC_AVATAR_GUILD_MEMBER_DATA_REQ", 0x00436150u },
    { "CPFsCharacter::fc_NC_CHARSAVE_ABSTATE_REQ", 0x00406850u },
    { "CPFsCharacter::fc_NC_CHARSAVE_ALL_REQ", 0x004064C0u },
    { "CPFsCharacter::fc_NC_CHARSAVE_DB_UI_STATE_SAVE_REQ", 0x00424300u },
    { "CPFsCharacter::fc_NC_CHARSAVE_ITEMACTIONCOOLTIME_REQ", 0x00424140u },
    { "CPFsCharacter::fc_NC_CHARSAVE_QUEST_DOING_REQ", 0x00406670u },
    { "CPFsCharacter::fc_NC_CHARSAVE_SET_CHAT_BLOCK_SPAMER_DB_CMD", 0x00423420u },
    { "CPFsCharacter::fc_NC_CHARSAVE_SKILL_REQ", 0x00406760u },
    { "CPFsCharacter::fc_NC_CHAR_CHARDATA_REQ", 0x00438DC0u },
    { "CPFsCharacter::fc_NC_CHAR_EVENT_ATTENDANCE_CHECK_DB_REQ", 0x00428130u },
    { "CPFsCharacter::fc_NC_CHAR_EVENT_ATTENDANCE_LIST_DB_REQ", 0x00427D90u },
    { "CPFsCharacter::fc_NC_CHAR_EVENT_ATTENDANCE_REWARD_DB_REQ", 0x00428290u },
    { "CPFsCharacter::fc_NC_CHAR_FREESTAT_SET_DB_REQ", 0x004135E0u },
    { "CPFsCharacter::fc_NC_CHAR_NEWBIE_GUIDE_VIEW_SET_DB_CMD", 0x004247A0u },
    { "CPFsCharacter::fc_NC_CHAR_OPTION_IMPROVE_DB_INIT_GAMEOPTION_REQ", 0x00422F10u },
    { "CPFsCharacter::fc_NC_CHAR_OPTION_IMPROVE_DB_INIT_KEYMAP_REQ", 0x00422890u },
    { "CPFsCharacter::fc_NC_CHAR_OPTION_IMPROVE_DB_SET_GAMEOPTION_REQ", 0x004231A0u },
    { "CPFsCharacter::fc_NC_CHAR_OPTION_IMPROVE_DB_SET_KEYMAP_REQ", 0x00422B80u },
    { "CPFsCharacter::fc_NC_CHAR_OPTION_IMPROVE_DB_SET_SHORTCUTDATA_REQ", 0x004224D0u },
    { "CPFsCharacter::fc_NC_CHAR_REGNUM_VARIFICATION_REQ", 0x00414170u },
    { "CPFsCharacter::fc_NC_CHAR_SET_STYLE_DB_REQ", 0x004182B0u },
    { "CPFsCharacter::fc_NC_CHAR_SET_STYLE_GET_INFO_DB_REQ", 0x00418840u },
    { "CPFsCharacter::fc_NC_CHAR_STAT_INCPOINT_DB_REQ", 0x004131A0u },
    { "CPFsCharacter::fc_NC_CHAR_TUTORIAL_FREESTAT_INIT_REQ", 0x00429C90u },
    { "CPFsCharacter::fc_NC_CHAR_TUTORIAL_MAKE_ITEM_REQ", 0x00429160u },
    { "CPFsCharacter::fc_NC_CHAR_TUTORIAL_STEP_SAVE_REQ", 0x00429AB0u },
    { "CPFsCharacter::fc_NC_CHAR_WEDDINGDATA_REQ", 0x00418A40u },
    { "CPFsCharacter::fc_NC_CHAR_WEDDING_DIVORCE_BY_AGREE_REQ", 0x00419250u },
    { "CPFsCharacter::fc_NC_CHAR_WEDDING_DIVORCE_BY_FORCE_REQ", 0x004193D0u },
    { "CPFsCharacter::fc_NC_CHAR_WEDDING_DIVORCE_CANCEL_REQ", 0x00419730u },
    { "CPFsCharacter::fc_NC_CHAR_WEDDING_DIVORCE_DO_REQ", 0x00419550u },
    { "CPFsCharacter::fc_NC_CHAR_WEDDING_DO_REQ", 0x00419920u },
    { "CPFsCharacter::fc_NC_CHAR_WEDDING_ESCAPE_DIVORCE_REQ", 0x00419140u },
    { "CPFsCharacter::fc_NC_CHAR_WEDDING_PARTNER_INFO_REQ", 0x00419AF0u },
    { "CPFsCharacter::fc_NC_CHAR_WEDDING_PROPOSE_CANCEL_REQ", 0x00418FC0u },
    { "CPFsCharacter::fc_NC_CHAR_WEDDING_PROPOSE_REQ", 0x00418E40u },
    { "CPFsCharacter::fc_NC_COLLECT_BOOKMARK_REGIST_DB_REQ", 0x004277A0u },
    { "CPFsCharacter::fc_NC_COLLECT_PEEPING_DB_REQ", 0x00427040u },
    { "CPFsCharacter::fc_NC_COLLECT_REGIST_REQ", 0x004275C0u },
    { "CPFsCharacter::fc_NC_COLLECT_REWARD_DB_REQ", 0x00427970u },
    { "CPFsCharacter::fc_NC_DICE_TAISAI_DB_DICE_ROLL_RESULT_REQ", 0x00420D50u },
    { "CPFsCharacter::fc_NC_DICE_TAISAI_DB_EXPECT_INCOME_MONEY_REQ", 0x00421190u },
    { "CPFsCharacter::fc_NC_DICE_TAISAI_DB_ITEM_ID_CHANGE_REQ", 0x00421660u },
    { "CPFsCharacter::fc_NC_DICE_TAISAI_DB_RANK_REQ", 0x00421420u },
    { "CPFsCharacter::fc_NC_DICE_TAISAI_DB_RECEIPT_INCOME_MONEY_REQ", 0x00435120u },
    { "CPFsCharacter::fc_NC_GAMBLE_COIN_DB_ADD_REQ", 0x004248B0u },
    { "CPFsCharacter::fc_NC_GAMBLE_COIN_DB_BUY_REQ", 0x00424BB0u },
    { "CPFsCharacter::fc_NC_GAMBLE_COIN_DB_SELL_REQ", 0x00424DD0u },
    { "CPFsCharacter::fc_NC_GAMBLE_COIN_DB_USE_COINITEM_REQ", 0x00424FC0u },
    { "CPFsCharacter::fc_NC_GAMBLE_DICE_TAISAI_DB_ALL_RANK_REQ", 0x00421E30u },
    { "CPFsCharacter::fc_NC_GAMBLE_DICE_TAISAI_DB_DICE_ROLL_RESULT_REQ", 0x00421A30u },
    { "CPFsCharacter::fc_NC_GAMBLE_EXCHANGEDCOIN_DB_INFO_REQ", 0x00424A40u },
    { "CPFsCharacter::fc_NC_GAMBLE_SLOTMACHINE_DB_GAMEINFO_REQ", 0x00425490u },
    { "CPFsCharacter::fc_NC_GAMBLE_SLOTMACHINE_DB_RESULT_REQ", 0x004251A0u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_ACADEMY_REWARD_REQ", 0x0041DE10u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_CLEAR_REWARD_MONEY_REQ", 0x0041D770u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_GET_GRADUATE_REQ", 0x004345F0u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_GET_RANKING_LIST_REQ", 0x00434BD0u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_GET_REWARD_ITEM_REQ", 0x0041CEF0u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_GRADUATE_JOIN_REQ", 0x0041D9F0u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_LEVEL_UP_REQ", 0x0041DCB0u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_MEMBER_GUILD_JOIN_REQ", 0x004377C0u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_MEMBER_JOIN_REQ", 0x0041BBD0u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_MEMBER_LEAVE_REQ", 0x0041BE10u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_MEMBER_REQ", 0x00437300u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_MEMBER_VANISH_REQ", 0x00437AB0u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_NOTIFY_REQ", 0x0041C000u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_RANK_BALANCE_REQ", 0x0041DB80u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_SET_MASTER_BY_LEAVE_REQ", 0x0041C3D0u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_SET_MASTER_REQ", 0x0041C1E0u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_SET_REWARD_ITEM_REQ", 0x0041D4C0u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_SET_REWARD_MONEY_REQ", 0x0041D290u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_HISTORY_DB_LIST_REQ", 0x00428DD0u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_MEMBER_DB_CHAT_BAN_CANCEL_REQ", 0x00428BF0u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_MEMBER_DB_CHAT_BAN_REQ", 0x0041ECF0u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_START_DB_ALL_REQ", 0x00434030u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_START_DB_GET_RANKING_LIST_REQ", 0x0041B5B0u },
    { "CPFsCharacter::fc_NC_GUILD_ACADEMY_START_DB_RANK_BALANCE_REQ", 0x0041B9E0u },
    { "CPFsCharacter::fc_NC_GUILD_DB_DELETE_CANCEL_REQ", 0x00415150u },
    { "CPFsCharacter::fc_NC_GUILD_DB_DELETE_REQ", 0x00414740u },
    { "CPFsCharacter::fc_NC_GUILD_DB_DISMISS_REQ", 0x00414900u },
    { "CPFsCharacter::fc_NC_GUILD_DB_INTRO_REQ", 0x00414EE0u },
    { "CPFsCharacter::fc_NC_GUILD_DB_LIST_REQ", 0x004332E0u },
    { "CPFsCharacter::fc_NC_GUILD_DB_MAKE_REQ", 0x00438440u },
    { "CPFsCharacter::fc_NC_GUILD_DB_MEMBER_GRADE_REQ", 0x00436A40u },
    { "CPFsCharacter::fc_NC_GUILD_DB_MEMBER_INTRO_REQ", 0x00415670u },
    { "CPFsCharacter::fc_NC_GUILD_DB_MEMBER_JOIN_REQ", 0x00415270u },
    { "CPFsCharacter::fc_NC_GUILD_DB_MEMBER_LEAVE_REQ", 0x00415480u },
    { "CPFsCharacter::fc_NC_GUILD_DB_MEMBER_REQ", 0x00432D90u },
    { "CPFsCharacter::fc_NC_GUILD_DB_MEMBER_VANISH_REQ", 0x00436820u },
    { "CPFsCharacter::fc_NC_GUILD_DB_MONEY_ADD_REQ", 0x00414A20u },
    { "CPFsCharacter::fc_NC_GUILD_DB_MONEY_SUB_REQ", 0x00414B80u },
    { "CPFsCharacter::fc_NC_GUILD_DB_NOTIFY_REQ", 0x00414CE0u },
    { "CPFsCharacter::fc_NC_GUILD_DB_RENAME_REQ", 0x0041F7E0u },
    { "CPFsCharacter::fc_NC_GUILD_DB_REQ", 0x00437E50u },
    { "CPFsCharacter::fc_NC_GUILD_DB_RETYPE_REQ", 0x0041F980u },
    { "CPFsCharacter::fc_NC_GUILD_DB_TOKEN_ALL_REQ", 0x004144E0u },
    { "CPFsCharacter::fc_NC_GUILD_DB_WAR_REQ", 0x00414FF0u },
    { "CPFsCharacter::fc_NC_GUILD_EMBLEM_INFO_DB_REQ", 0x0042F3A0u },
    { "CPFsCharacter::fc_NC_GUILD_EMBLEM_SAVE_DB_REQ", 0x0042F730u },
    { "CPFsCharacter::fc_NC_GUILD_EMBLEM_STATE_DB_REQ", 0x0042F970u },
    { "CPFsCharacter::fc_NC_GUILD_HISTORY_DB_LIST_REQ", 0x00435630u },
    { "CPFsCharacter::fc_NC_GUILD_TOURNAMENT_DB_FINAL_SELECTION_REQ", 0x00408630u },
    { "CPFsCharacter::fc_NC_GUILD_TOURNAMENT_DB_GET_REQ", 0x004159D0u },
    { "CPFsCharacter::fc_NC_GUILD_TOURNAMENT_DB_JOIN_LIST_REQ", 0x004083D0u },
    { "CPFsCharacter::fc_NC_GUILD_TOURNAMENT_DB_JOIN_NEW_REQ", 0x00408180u },
    { "CPFsCharacter::fc_NC_GUILD_TOURNAMENT_DB_REWARD_CREATE_REQ", 0x004076A0u },
    { "CPFsCharacter::fc_NC_GUILD_TOURNAMENT_DB_SET_MATCH_REQ", 0x00415CF0u },
    { "CPFsCharacter::fc_NC_GUILD_TOURNAMENT_DB_SET_MATCH_TIME_REQ", 0x00415E70u },
    { "CPFsCharacter::fc_NC_GUILD_TOURNAMENT_DB_SET_REQ", 0x00415FE0u },
    { "CPFsCharacter::fc_NC_GUILD_TOURNAMENT_DB_SET_RESULT_REQ", 0x004161C0u },
    { "CPFsCharacter::fc_NC_GUILD_TOURNAMENT_DB_SET_TYPE_REQ", 0x004164F0u },
    { "CPFsCharacter::fc_NC_GUILD_TOURNAMENT_ENTER_LIST_DB_GET_REQ", 0x00408890u },
    { "CPFsCharacter::fc_NC_GUILD_TOURNAMENT_REFUND_NOTICE_DB_SET_REQ", 0x00408AE0u },
    { "CPFsCharacter::fc_NC_HOLY_PROMISE_DB_GET_CEN_REWARD_REQ", 0x0041AFF0u },
    { "CPFsCharacter::fc_NC_HOLY_PROMISE_DB_REWARD_REQ", 0x0041A900u },
    { "CPFsCharacter::fc_NC_HOLY_PROMISE_DB_SET_DATE_REQ", 0x0041AE00u },
    { "CPFsCharacter::fc_NC_HOLY_PROMISE_DB_WITHDRAW_CEN_REWARD_REQ", 0x0041B190u },
    { "CPFsCharacter::fc_NC_ITEMDB_BOOTHTRADE_ALL_REQ", 0x0040F510u },
    { "CPFsCharacter::fc_NC_ITEMDB_BOOTHTRADE_LOT_REQ", 0x0040FEB0u },
    { "CPFsCharacter::fc_NC_ITEMDB_BOOTHTRADE_MERGE_REQ", 0x0040F950u },
    { "CPFsCharacter::fc_NC_ITEMDB_BRACELET_UPGRADE_REQ", 0x00430E70u },
    { "CPFsCharacter::fc_NC_ITEMDB_BUYCAPSULE_REQ", 0x00425900u },
    { "CPFsCharacter::fc_NC_ITEMDB_CAPSULEITEM_REQ", 0x00425DD0u },
    { "CPFsCharacter::fc_NC_ITEMDB_CHARGED_LIST_REQ", 0x004116E0u },
    { "CPFsCharacter::fc_NC_ITEMDB_CHARGED_WITHDRAW_REQ", 0x004118A0u },
    { "CPFsCharacter::fc_NC_ITEMDB_CHAT_COLOR_CHANGE_REQ", 0x0042CFC0u },
    { "CPFsCharacter::fc_NC_ITEMDB_CHESTITEM_REQ", 0x0040F030u },
    { "CPFsCharacter::fc_NC_ITEMDB_CLASS_CHANGE_REQ", 0x0042E6B0u },
    { "CPFsCharacter::fc_NC_ITEMDB_DEPOSIT_REQ", 0x00410FA0u },
    { "CPFsCharacter::fc_NC_ITEMDB_DESTROY_REQ", 0x004325E0u },
    { "CPFsCharacter::fc_NC_ITEMDB_DISMANTLE_REQ", 0x00419C00u },
    { "CPFsCharacter::fc_NC_ITEMDB_ENCHANT_ADD_GEM_REQ", 0x00423500u },
    { "CPFsCharacter::fc_NC_ITEMDB_ENCHANT_ADD_NEW_SOCKET_REQ", 0x00423930u },
    { "CPFsCharacter::fc_NC_ITEMDB_ENCHANT_REMOVE_GEM_REQ", 0x004236E0u },
    { "CPFsCharacter::fc_NC_ITEMDB_ENCHANT_SET_GEM_LOT_REQ", 0x00423B90u },
    { "CPFsCharacter::fc_NC_ITEMDB_EQUIP_BELONGED_CANCEL_USE_REQ", 0x00426460u },
    { "CPFsCharacter::fc_NC_ITEMDB_EQUIP_REQ", 0x0040A8F0u },
    { "CPFsCharacter::fc_NC_ITEMDB_FURNITURE_ENDURE_REQ", 0x0041FAD0u },
    { "CPFsCharacter::fc_NC_ITEMDB_GETFROMCAPSULE_REQ", 0x00426050u },
    { "CPFsCharacter::fc_NC_ITEMDB_GUILD_ACADEMY_REWARD_STORAGE_DEPOSIT_REQ", 0x0041CAA0u },
    { "CPFsCharacter::fc_NC_ITEMDB_GUILD_ACADEMY_REWARD_STORAGE_OPEN_REQ", 0x0041C580u },
    { "CPFsCharacter::fc_NC_ITEMDB_GUILD_ACADEMY_REWARD_STORAGE_WITHDRAW_REQ", 0x0041C880u },
    { "CPFsCharacter::fc_NC_ITEMDB_GUILD_STORAGE_WITHDRAW_REQ", 0x00411460u },
    { "CPFsCharacter::fc_NC_ITEMDB_ITEMBREAK_REQ", 0x00411C90u },
    { "CPFsCharacter::fc_NC_ITEMDB_ITEMINFO_REQ", 0x004269B0u },
    { "CPFsCharacter::fc_NC_ITEMDB_ITEMMONEY_BUYALL_REQ", 0x0042A6D0u },
    { "CPFsCharacter::fc_NC_ITEMDB_ITEMMONEY_BUYLOT_REQ", 0x0042AEB0u },
    { "CPFsCharacter::fc_NC_ITEMDB_ITEMREBUILD_REQ", 0x00426C20u },
    { "CPFsCharacter::fc_NC_ITEMDB_ITEMTOTALINFORM_REQ", 0x00431EA0u },
    { "CPFsCharacter::fc_NC_ITEMDB_MAPLINK_ITEM_CONSUME_REQ", 0x0042FD10u },
    { "CPFsCharacter::fc_NC_ITEMDB_MINIHOUSE_EFFECT_DEMANDGOOD_REQ", 0x0041A230u },
    { "CPFsCharacter::fc_NC_ITEMDB_MIX_ITEM_REQ", 0x00430380u },
    { "CPFsCharacter::fc_NC_ITEMDB_MOVER_RAREMOVER_REQ", 0x0042A230u },
    { "CPFsCharacter::fc_NC_ITEMDB_MOVER_UPGRADE_REQ", 0x00429E70u },
    { "CPFsCharacter::fc_NC_ITEMDB_OPENSTORAGE_REQ", 0x0040DA60u },
    { "CPFsCharacter::fc_NC_ITEMDB_OPEN_GUILD_STORAGE_REQ", 0x0040DD30u },
    { "CPFsCharacter::fc_NC_ITEMDB_PRODUCE_REQ", 0x004324F0u },
    { "CPFsCharacter::fc_NC_ITEMDB_QUESTITEMGET_REQ", 0x0040E630u },
    { "CPFsCharacter::fc_NC_ITEMDB_QUESTREWARD_REQ", 0x00432770u },
    { "CPFsCharacter::fc_NC_ITEMDB_RANDOMOPTION_CHANGE_CONSUME_AND_COUNTING_REQ", 0x0042C120u },
    { "CPFsCharacter::fc_NC_ITEMDB_RANDOMOPTION_CHANGE_REQ", 0x004359C0u },
    { "CPFsCharacter::fc_NC_ITEMDB_RANDOMOPTION_RECOVER_COUNT_LIMIT_REQ", 0x0042C750u },
    { "CPFsCharacter::fc_NC_ITEMDB_REPURCHASE_ALL_REQ", 0x0042E060u },
    { "CPFsCharacter::fc_NC_ITEMDB_REPURCHASE_LOT_REQ", 0x0042E380u },
    { "CPFsCharacter::fc_NC_ITEMDB_SELLALL_REQ", 0x00409A20u },
    { "CPFsCharacter::fc_NC_ITEMDB_SHIELDENDURE_CHARGE_REQ", 0x0041FFA0u },
    { "CPFsCharacter::fc_NC_ITEMDB_TERMEXTEND_REQ", 0x0042D500u },
    { "CPFsCharacter::fc_NC_ITEMDB_UES_FRIEND_POINT_REQ", 0x0042EF20u },
    { "CPFsCharacter::fc_NC_ITEMDB_WEAPONENDURE_CHARGE_REQ", 0x0041FCF0u },
    { "CPFsCharacter::fc_NC_ITEMDB_WITHDRAW_REQ", 0x00411200u },
    { "CPFsCharacter::fc_NC_KQ_REWARD_REQ", 0x004321D0u },
    { "CPFsCharacter::fc_NC_MINIHOUSE_DB_OWNERBLOG_GET_REQ", 0x00417AC0u },
    { "CPFsCharacter::fc_NC_MINIHOUSE_DB_OWNERBLOG_SET_REQ", 0x00417C80u },
    { "CPFsCharacter::fc_NC_MINIHOUSE_DB_PORTAL_ADD_REQ", 0x00433E80u },
    { "CPFsCharacter::fc_NC_MINIHOUSE_DB_PORTAL_DEL_REQ", 0x00417DF0u },
    { "CPFsCharacter::fc_NC_MINIHOUSE_DB_PORTAL_LIST_REQ", 0x00433BB0u },
    { "CPFsCharacter::fc_NC_MINIHOUSE_DB_VISITER_COUNT_REQ", 0x00417F50u },
    { "CPFsCharacter::fc_NC_MISC_SET_CHAT_BLOCK_SPAM_FILTER_DB_CMD", 0x00423320u },
    { "CPFsCharacter::fc_NC_MISC_SPAMMER_RELEASE_CHAT_BAN_DB_REQ", 0x004245F0u },
    { "CPFsCharacter::fc_NC_MISC_SPAMMER_SET_DB_CHAT_BAN_REQ", 0x00424450u },
    { "CPFsCharacter::fc_NC_OPTOOL_CONNECT_BRIF_REQ", 0x0043D180u },
    { "CPFsCharacter::fc_NC_OPTOOL_MAP_USER_LIST_REQ", 0x0043D0B0u },
    { "CPFsCharacter::fc_NC_OPTOOL_S2SCONNECT_LIST_REQ", 0x0043CE10u },
    { "CPFsCharacter::fc_NC_PET_CREATE_DB_REQ", 0x0042B6B0u },
    { "CPFsCharacter::fc_NC_PET_LOAD_INFO_DB_REQ", 0x0042BCC0u },
    { "CPFsCharacter::fc_NC_PET_REMOVE_DB_REQ", 0x0042BF30u },
    { "CPFsCharacter::fc_NC_PET_SET_NAME_DB_REQ", 0x0042BA70u },
    { "CPFsCharacter::fc_NC_PET_SET_TENDENCY_DB_REQ", 0x0042B920u },
    { "CPFsCharacter::fc_NC_PROMOTION_DB_REWARD_REQ", 0x0041EFF0u },
    { "CPFsCharacter::fc_NC_QUEST_DB_CLEAR_REQ", 0x00406EB0u },
    { "CPFsCharacter::fc_NC_QUEST_DB_DONE_REQ", 0x00431550u },
    { "CPFsCharacter::fc_NC_QUEST_DB_GIVE_UP_REQ", 0x00407050u },
    { "CPFsCharacter::fc_NC_QUEST_DB_READ_REQ", 0x00407230u },
    { "CPFsCharacter::fc_NC_QUEST_DB_SET_INFO_REQ", 0x00406D00u },
    { "CPFsCharacter::fc_NC_USER_AVATARINFO_REQ", 0x004050B0u },
    { "CProtocol_Functions::fc_NC_MISC_S2SCONNECTION_REQ", 0x0043C880u },
    { "CSQLPCharacter::usp_Attendance_getCallDateList", 0x0045F3D0u },
    { "CSQLPCharacter::usp_Attendance_getCount", 0x0045F630u },
    { "CSQLPCharacter::usp_Attendance_getRewardList", 0x0045F770u },
    { "CSQLPCharacter::usp_Attendance_setCall", 0x0045F510u },
    { "CSQLPCharacter::usp_Attendance_setReward", 0x0045F890u },
    { "CSQLPCharacter::usp_Char_GetCharSingleOption", 0x0045C0E0u },
    { "CSQLPCharacter::usp_Character_GetDiffFriendpoint", 0x00460840u },
    { "CSQLPCharacter::usp_Character_getAutoScroll", 0x00460260u },
    { "CSQLPCharacter::usp_Character_getChangeIDList", 0x0045E5F0u },
    { "CSQLPCharacter::usp_Character_getFriendpoint", 0x00460600u },
    { "CSQLPCharacter::usp_Character_setBuffScroll", 0x00460000u },
    { "CSQLPCharacter::usp_Character_setChargedbuffScroll", 0x00460130u },
    { "CSQLPCharacter::usp_Character_setChatBan", 0x0045E920u },
    { "CSQLPCharacter::usp_Character_setFriendpoint", 0x00460710u },
    { "CSQLPCharacter::usp_Character_setMysteryBolt", 0x0045C2B0u },
    { "CSQLPCharacter::usp_ChatColor_get", 0x0045FC90u },
    { "CSQLPCharacter::usp_ChatColor_setBalloon", 0x0045FED0u },
    { "CSQLPCharacter::usp_ChatColor_setFont", 0x0045FDA0u },
    { "CSQLPCharacter::usp_InGameGuide_getViewList", 0x0045EA60u },
    { "CSQLPCharacter::usp_InGameGuide_setGuideNo", 0x0045EAF0u },
    { "CSQLPCharacter::usp_Item_getAutoMonList", 0x004604D0u },
    { "CSQLPCharacter::usp_Item_setAutoMon", 0x00460370u },
    { "CSQLPCharacter::usp_Item_setPutOnBelonged", 0x004644D0u },
    { "CSQLPCharacter::usp_Item_setPutOnBelongedCancel", 0x004649A0u },
    { "CSQLPCharacter::usp_Item_setPutOnBelongedExchange", 0x00464710u },
    { "CSQLPCharacter::usp_LinkScroll_SetDestMap", 0x00460950u },
    { "CSQLPCharacter::usp_SpamBlock_getTime", 0x0045E380u },
    { "CSQLPCharacter::usp_SpamBlock_setTime", 0x0045E4B0u },
    { "CSQLPCharacter::usp_SpamFilter_get", 0x0045E100u },
    { "CSQLPCharacter::usp_SpamFilter_set", 0x0045E230u },
    { "CSQLPCharacter::usp_Tutorial_getCharInfo", 0x0045FA80u },
    { "CSQLPCharacter::usp_Tutorial_getIsSkip", 0x0045F9D0u },
    { "CSQLPCharacter::usp_Tutorial_setCharInfo", 0x0045FB30u },
    { "CSQLPCollection::usp_Collection_getCardList", 0x00466970u },
    { "CSQLPCollection::usp_Collection_getFavoritesList", 0x00466A70u },
    { "CSQLPCollection::usp_Collection_getRewardList", 0x00466F50u },
    { "CSQLPCollection::usp_Collection_getSerialList", 0x00467170u },
    { "CSQLPCollection::usp_Collection_setCard", 0x00466B70u },
    { "CSQLPCollection::usp_Collection_setFavorites", 0x00466CE0u },
    { "CSQLPCollection::usp_Collection_setReward", 0x00466E30u },
    { "CSQLPCollection::usp_Collection_setSerial", 0x00467050u },
    { "CSQLPGambleHouse::usp_Gamble_AddCoin", 0x00466320u },
    { "CSQLPGambleHouse::usp_Gamble_GetCoin", 0x00466220u },
    { "CSQLPGambleHouse::usp_Gamble_GetExchangedCoin", 0x004663F0u },
    { "CSQLPGambleHouse::usp_Gamble_SetCoinToMoney", 0x00466610u },
    { "CSQLPGambleHouse::usp_Gamble_SetMoneyToCoin", 0x00466510u },
    { "CSQLPGambleHouse::usp_Gamble_getJackpotCoin", 0x004668E0u },
    { "CSQLPGambleHouse::usp_Gamble_getJackpotRanking", 0x00466830u },
    { "CSQLPGambleHouse::usp_Gamble_setSlotMachineResult", 0x004666E0u },
    { "CSQLPGuild::usp_GuildAcademy_getHistoryList", 0x00457250u },
    { "CSQLPGuild::usp_GuildAcademy_setHistory", 0x00457370u },
    { "CSQLPGuild::usp_GuildTournament_Final_Selection", 0x004551B0u },
    { "CSQLPGuild::usp_GuildTournament_Final_Selection_List", 0x004553C0u },
    { "CSQLPGuild::usp_GuildTournament_Join_List", 0x004550B0u },
    { "CSQLPGuild::usp_GuildTournament_Join_New", 0x00454E40u },
    { "CSQLPGuild::usp_GuildTournament_Refund_Notice_Set", 0x00455590u },
    { "CSQLPGuild::usp_GuildTournament_Set_Result", 0x004556B0u },
    { "CSQLPGuild::usp_Guild_getHistoryList", 0x00456FD0u },
    { "CSQLPGuild::usp_Guild_setHistory", 0x004570F0u },
    { "CSQLPHolyPromise::usp_HolyPromise_getRemainMoney", 0x00457DF0u },
    { "CSQLPHolyPromise::usp_HolyPromise_setMoney", 0x00457BD0u },
    { "CSQLPItem::usp_Item_setPutOnBelongedCancel", 0x004649A0u },
    { "CSQLPPet::usp_Pet_getInfo", 0x00467670u },
    { "CSQLPPet::usp_Pet_setCreate", 0x00467260u },
    { "CSQLPPet::usp_Pet_setDelete", 0x00467810u },
    { "CSQLPPet::usp_Pet_setName", 0x00467430u },
    { "CSQLPPet::usp_Pet_setTendency", 0x00467540u },
    { "CSQLPUserConnection::usp_Character_setChangeID", 0x00465F30u },
    { "CSQLPUserConnection::usp_Character_setChangeIDItemUsed", 0x004660A0u },
};
static const int kHandlerCount = 269;

// Of these, named by the one _ACK they build (they log no name of their own): 67
//   CPFsCharacter::fc_NC_AVATAR_GUILD_DATA_REQ
//   CPFsCharacter::fc_NC_CHARSAVE_ABSTATE_REQ
//   CPFsCharacter::fc_NC_CHARSAVE_QUEST_DOING_REQ
//   CPFsCharacter::fc_NC_CHARSAVE_SKILL_REQ
//   CPFsCharacter::fc_NC_CHAR_SET_STYLE_DB_REQ
//   CPFsCharacter::fc_NC_CHAR_SET_STYLE_GET_INFO_DB_REQ
//   CPFsCharacter::fc_NC_CHAR_WEDDINGDATA_REQ
//   CPFsCharacter::fc_NC_CHAR_WEDDING_DIVORCE_BY_AGREE_REQ
//   CPFsCharacter::fc_NC_CHAR_WEDDING_DIVORCE_BY_FORCE_REQ
//   CPFsCharacter::fc_NC_CHAR_WEDDING_DIVORCE_CANCEL_REQ
//   CPFsCharacter::fc_NC_CHAR_WEDDING_DIVORCE_DO_REQ
//   CPFsCharacter::fc_NC_CHAR_WEDDING_DO_REQ
//   CPFsCharacter::fc_NC_CHAR_WEDDING_ESCAPE_DIVORCE_REQ
//   CPFsCharacter::fc_NC_CHAR_WEDDING_PARTNER_INFO_REQ
//   CPFsCharacter::fc_NC_CHAR_WEDDING_PROPOSE_CANCEL_REQ
//   CPFsCharacter::fc_NC_CHAR_WEDDING_PROPOSE_REQ
//   CPFsCharacter::fc_NC_DICE_TAISAI_DB_DICE_ROLL_RESULT_REQ
//   CPFsCharacter::fc_NC_DICE_TAISAI_DB_EXPECT_INCOME_MONEY_REQ
//   CPFsCharacter::fc_NC_DICE_TAISAI_DB_ITEM_ID_CHANGE_REQ
//   CPFsCharacter::fc_NC_DICE_TAISAI_DB_RANK_REQ
//   CPFsCharacter::fc_NC_DICE_TAISAI_DB_RECEIPT_INCOME_MONEY_REQ
//   CPFsCharacter::fc_NC_GAMBLE_DICE_TAISAI_DB_ALL_RANK_REQ
//   CPFsCharacter::fc_NC_GAMBLE_DICE_TAISAI_DB_DICE_ROLL_RESULT_REQ
//   CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_GRADUATE_JOIN_REQ
//   CPFsCharacter::fc_NC_GUILD_EMBLEM_INFO_DB_REQ
//   CPFsCharacter::fc_NC_GUILD_EMBLEM_SAVE_DB_REQ
//   CPFsCharacter::fc_NC_GUILD_EMBLEM_STATE_DB_REQ
//   CPFsCharacter::fc_NC_GUILD_TOURNAMENT_DB_SET_MATCH_REQ
//   CPFsCharacter::fc_NC_GUILD_TOURNAMENT_DB_SET_MATCH_TIME_REQ
//   CPFsCharacter::fc_NC_GUILD_TOURNAMENT_DB_SET_REQ
//   CPFsCharacter::fc_NC_GUILD_TOURNAMENT_DB_SET_RESULT_REQ
//   CPFsCharacter::fc_NC_GUILD_TOURNAMENT_DB_SET_TYPE_REQ
//   CPFsCharacter::fc_NC_HOLY_PROMISE_DB_REWARD_REQ
//   CPFsCharacter::fc_NC_ITEMDB_BRACELET_UPGRADE_REQ
//   CPFsCharacter::fc_NC_ITEMDB_BUYCAPSULE_REQ
//   CPFsCharacter::fc_NC_ITEMDB_CAPSULEITEM_REQ
//   CPFsCharacter::fc_NC_ITEMDB_CHARGED_LIST_REQ
//   CPFsCharacter::fc_NC_ITEMDB_CHARGED_WITHDRAW_REQ
//   CPFsCharacter::fc_NC_ITEMDB_CHESTITEM_REQ
//   CPFsCharacter::fc_NC_ITEMDB_DEPOSIT_REQ
//   CPFsCharacter::fc_NC_ITEMDB_DESTROY_REQ
//   CPFsCharacter::fc_NC_ITEMDB_DISMANTLE_REQ
//   CPFsCharacter::fc_NC_ITEMDB_FURNITURE_ENDURE_REQ
//   CPFsCharacter::fc_NC_ITEMDB_GETFROMCAPSULE_REQ
//   CPFsCharacter::fc_NC_ITEMDB_GUILD_ACADEMY_REWARD_STORAGE_DEPOSIT_REQ
//   CPFsCharacter::fc_NC_ITEMDB_GUILD_ACADEMY_REWARD_STORAGE_WITHDRAW_REQ
//   CPFsCharacter::fc_NC_ITEMDB_GUILD_STORAGE_WITHDRAW_REQ
//   CPFsCharacter::fc_NC_ITEMDB_ITEMINFO_REQ
//   CPFsCharacter::fc_NC_ITEMDB_ITEMTOTALINFORM_REQ
//   CPFsCharacter::fc_NC_ITEMDB_PRODUCE_REQ
//   CPFsCharacter::fc_NC_ITEMDB_QUESTREWARD_REQ
//   CPFsCharacter::fc_NC_ITEMDB_REPURCHASE_ALL_REQ
//   CPFsCharacter::fc_NC_ITEMDB_REPURCHASE_LOT_REQ
//   CPFsCharacter::fc_NC_ITEMDB_SHIELDENDURE_CHARGE_REQ
//   CPFsCharacter::fc_NC_ITEMDB_WEAPONENDURE_CHARGE_REQ
//   CPFsCharacter::fc_NC_ITEMDB_WITHDRAW_REQ
//   CPFsCharacter::fc_NC_MINIHOUSE_DB_OWNERBLOG_GET_REQ
//   CPFsCharacter::fc_NC_MINIHOUSE_DB_OWNERBLOG_SET_REQ
//   CPFsCharacter::fc_NC_OPTOOL_CONNECT_BRIF_REQ
//   CPFsCharacter::fc_NC_OPTOOL_MAP_USER_LIST_REQ
//   CPFsCharacter::fc_NC_OPTOOL_S2SCONNECT_LIST_REQ
//   CPFsCharacter::fc_NC_PROMOTION_DB_REWARD_REQ
//   CPFsCharacter::fc_NC_QUEST_DB_CLEAR_REQ
//   CPFsCharacter::fc_NC_QUEST_DB_DONE_REQ
//   CPFsCharacter::fc_NC_QUEST_DB_GIVE_UP_REQ
//   CPFsCharacter::fc_NC_QUEST_DB_READ_REQ
//   CPFsCharacter::fc_NC_QUEST_DB_SET_INFO_REQ

// Named in a log string but used by more than one function, so not assigned: 4
//   CPFsCharacter::fc_NC_CT_DB_SET_CMD
//   CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_CLEAR_REWARD_ITEM_REQ
//   CPFsCharacter::fc_NC_GUILD_ACADEMY_DB_GET_REWARD_MONEY_REQ
//   CPFsCharacter::fc_NC_ITEMDB_MAPLINK_ITEM_COMPARE_MAP_REQ

// Framework functions (Account.pdb names, matched by bytes). 0 = no UNIQUE match - not guessed.
static const unsigned int kVa_CPFs_CheckConnectionValidation = 0x0043C640u;   // unique byte match
static const unsigned int kVa_DBRecord_bindColumns = 0x00000000u;   // NOT FOUND
static const unsigned int kVa_DBRecord_close = 0x0044FAD0u;   // unique byte match
static const unsigned int kVa_DBRecord_endFetch = 0x0044FBC0u;   // same layout as DBRecord_query, bytes verified at the address
static const unsigned int kVa_DBRecord_fetch = 0x0044FB90u;   // unique byte match
static const unsigned int kVa_DBRecord_getStatement = 0x0044FDD0u;   // same layout as DBRecord_openDB, bytes verified at the address
static const unsigned int kVa_DBRecord_openDB = 0x0044FE60u;   // unique byte match
static const unsigned int kVa_DBRecord_query = 0x0044FB00u;   // unique byte match
static const unsigned int kVa_DBRecord_readInt = 0x0044FBD0u;   // unique byte match
static const unsigned int kVa_DBRecord_readULong = 0x0044FC60u;   // unique byte match
static const unsigned int kVa_Database_CommitTran = 0x00451E70u;   // unique byte match
static const unsigned int kVa_Database_InitEnv = 0x00451DD0u;   // unique byte match
static const unsigned int kVa_Database_close = 0x00451FD0u;   // unique byte match
static const unsigned int kVa_Database_openDB = 0x00452080u;   // unique byte match

// Typed accessors. __thiscall is spelled __fastcall with a dead edx (same ABI, callee-clean).
namespace fn {

// public: int __thiscall CPFs::CheckConnectionValidation(struct NETPACKET *)
typedef int (__fastcall* CPFs_CheckConnectionValidation_t)(void* self, void* edx, void* a1);
inline CPFs_CheckConnectionValidation_t CPFs_CheckConnectionValidation() { return (CPFs_CheckConnectionValidation_t)::hook::rebase(kVa_CPFs_CheckConnectionValidation, kImageBase); }

// DBRecord_bindColumns: not found in this exe
// public: void __thiscall DBRecord::close(void)
typedef void (__fastcall* DBRecord_close_t)(void* self, void* edx);
inline DBRecord_close_t DBRecord_close() { return (DBRecord_close_t)::hook::rebase(kVa_DBRecord_close, kImageBase); }

// public: void __thiscall DBRecord::endFetch(void)
typedef void (__fastcall* DBRecord_endFetch_t)(void* self, void* edx);
inline DBRecord_endFetch_t DBRecord_endFetch() { return (DBRecord_endFetch_t)::hook::rebase(kVa_DBRecord_endFetch, kImageBase); }

// public: bool __thiscall DBRecord::fetch(void)
typedef bool (__fastcall* DBRecord_fetch_t)(void* self, void* edx);
inline DBRecord_fetch_t DBRecord_fetch() { return (DBRecord_fetch_t)::hook::rebase(kVa_DBRecord_fetch, kImageBase); }

// public: void * __thiscall DBRecord::getStatement(void)
typedef void* (__fastcall* DBRecord_getStatement_t)(void* self, void* edx);
inline DBRecord_getStatement_t DBRecord_getStatement() { return (DBRecord_getStatement_t)::hook::rebase(kVa_DBRecord_getStatement, kImageBase); }

// public: virtual bool __thiscall DBRecord::openDB(char *)
typedef bool (__fastcall* DBRecord_openDB_t)(void* self, void* edx, char* a1);
inline DBRecord_openDB_t DBRecord_openDB() { return (DBRecord_openDB_t)::hook::rebase(kVa_DBRecord_openDB, kImageBase); }

// public: bool __cdecl DBRecord::query(char const *,...)
typedef bool (__cdecl* DBRecord_query_t)(void* self, char* a1, ...);
inline DBRecord_query_t DBRecord_query() { return (DBRecord_query_t)::hook::rebase(kVa_DBRecord_query, kImageBase); }

// public: class DBRecord & __thiscall DBRecord::operator>>(int &)
typedef void* (__fastcall* DBRecord_readInt_t)(void* self, void* edx, int* a1);
inline DBRecord_readInt_t DBRecord_readInt() { return (DBRecord_readInt_t)::hook::rebase(kVa_DBRecord_readInt, kImageBase); }

// public: class DBRecord & __thiscall DBRecord::operator>>(unsigned long &)
typedef void* (__fastcall* DBRecord_readULong_t)(void* self, void* edx, unsigned long* a1);
inline DBRecord_readULong_t DBRecord_readULong() { return (DBRecord_readULong_t)::hook::rebase(kVa_DBRecord_readULong, kImageBase); }

// public: bool __thiscall Database::CommitTran(void)
typedef bool (__fastcall* Database_CommitTran_t)(void* self, void* edx);
inline Database_CommitTran_t Database_CommitTran() { return (Database_CommitTran_t)::hook::rebase(kVa_Database_CommitTran, kImageBase); }

// protected: bool __thiscall Database::InitEnv(void)
typedef bool (__fastcall* Database_InitEnv_t)(void* self, void* edx);
inline Database_InitEnv_t Database_InitEnv() { return (Database_InitEnv_t)::hook::rebase(kVa_Database_InitEnv, kImageBase); }

// public: void __thiscall Database::close(void)
typedef void (__fastcall* Database_close_t)(void* self, void* edx);
inline Database_close_t Database_close() { return (Database_close_t)::hook::rebase(kVa_Database_close, kImageBase); }

// public: virtual bool __thiscall Database::openDB(char *)
typedef bool (__fastcall* Database_openDB_t)(void* self, void* edx, char* a1);
inline Database_openDB_t Database_openDB() { return (Database_openDB_t)::hook::rebase(kVa_Database_openDB, kImageBase); }

// ItemListReader - found by reading the disassembly: reads bag `type` of `owner` (p_Item_GetListType) into 40-byte records, at most `limit`; __thiscall on dbf+0x24, ret 0x18. Every per-bag wrapper (0x46A290 bag 9 limit 0x90, 0x46A2C0 bag 8 ...) calls it; refuses type >= 0x11 unless char-itemlist-void widened it.
typedef int (__fastcall* ItemListReader_t)(void* ecx, void* edx, void* dbf, unsigned long owner, int type, int limit, int* count, void* records);
static const unsigned int kVa_ItemListReader = 0x00469F70u;
inline ItemListReader_t ItemListReader() { return (ItemListReader_t)::hook::rebase(kVa_ItemListReader, kImageBase); }

// ItemListPack - found by reading the disassembly: packs a reader list {int count; int pad; records} into the zone wire form {.., u8 count, items}; __thiscall on the handler's CPFs, ret 0xC.
typedef int (__fastcall* ItemListPack_t)(void* cpfs, void* edx, void* list, unsigned char* out, int* len);
static const unsigned int kVa_ItemListPack = 0x00402E50u;
inline ItemListPack_t ItemListPack() { return (ItemListPack_t)::hook::rebase(kVa_ItemListPack, kImageBase); }

// InventoryPacker - found by reading the disassembly: bag 9 end to end: reader (limit 144, a stack buffer sized for exactly that) + ItemListPack. Called by fc_NC_CHAR_CHARDATA_REQ (login) and GET_ITEMLIST_BY_TYPE case 9. char_void replaces it (192).
typedef int (__fastcall* InventoryPacker_t)(void* cpfs, void* edx, unsigned long owner, unsigned char* out, int* len);
static const unsigned int kVa_InventoryPacker = 0x00402F80u;
inline InventoryPacker_t InventoryPacker() { return (InventoryPacker_t)::hook::rebase(kVa_InventoryPacker, kImageBase); }

}  // namespace fn

// The bytes each disassembly-found function starts with, for chr::verify_known() (charhook.h):
// the header was generated from one exe; a plugin runs in whichever one is deployed.
struct KnownHead { const char* name; unsigned int va; unsigned char head[16]; unsigned int n; };
static const KnownHead kKnownHeads[] = {
    { "ItemListReader", 0x00469F70u, { 0x55, 0x8B, 0xEC, 0x8B, 0x45, 0x10, 0x56 }, 7 },
    { "ItemListPack", 0x00402E50u, { 0x55, 0x8B, 0xEC, 0x81, 0xEC, 0x88, 0x00, 0x00, 0x00 }, 9 },
    { "InventoryPacker", 0x00402F80u, { 0x55, 0x8B, 0xEC, 0xB8, 0x8C, 0x16, 0x00, 0x00 }, 8 },
};
static const int kKnownCount = 3;

// CSessionWorker::m_DBF - each worker thread's own, already-connected DBRecord. Read off every call to a
// stored-procedure wrapper (add reg, <this> before the call): 33 call sites, all agreeing.
static const unsigned int kWorkerDbfOffset = 0x124C;

}  // namespace chr
