// charhook.h - hooking Character.exe, the Character DB bridge. The core (detour, vtable, IAT, logging,
// plugins) is hook_core.h; this adds Character's handlers and the objects a handler works with. For the
// database side see dbhook.h.
//
//     #include <charhook.h>
//
//     CHAR_HOOK_HANDLER(fc_NC_CHARSAVE_ALL_REQ, {
//         chr::log("save for worker %x", chr::worker_of(self));
//         return CHAR_CALL_ORIGINAL_OF(fc_NC_CHARSAVE_ALL_REQ);   // omit to swallow the request
//     });
//
//     HOOK_PLUGIN("my_feature") {
//         CHAR_INSTALL_HANDLER(fc_NC_CHARSAVE_ALL_REQ);
//     }
//
// THERE IS NO Character.pdb. Every address comes from character_symbols.h, generated by
// tools/mk_char_symbols.py: handler names from the log strings each handler writes (131 handlers, every one
// checked for the handler shape - `ret 8` and an early CPFs::CheckConnectionValidation), and the framework
// functions from Account.pdb, found here by their bytes. Account, AccountLog and Character share one
// DB-bridge framework, so Account.pdb's layouts are the layouts used below.
#pragma once
#include "hook_core.h"
#include "character_symbols.h"

namespace chr {

using namespace ::hook;

// ---- the objects a handler is given ----------------------------------------------------------------
//
// A handler is `int __thiscall CPFsCharacter::fc_NC_<NAME>(NETPACKET*, int)`. Its `this` is a CPFs, which
// Account.pdb lays out as { CSessionWorker* m_pSessionWorker; CSession* m_pSession; } - 8 bytes, no vtable.
// The worker is the thread the request runs on; it owns that thread's parser and its DB object.

// The worker a handler is running on. `self` is the handler's `this`.
inline void* worker_of(void* self) { return self ? ((void**)self)[0] : NULL; }

// The session (the S2S connection) the request came in on - where a reply goes.
inline void* session_of(void* self) { return self ? ((void**)self)[1] : NULL; }

// NETPACKET is the 2-byte NETCOMMAND (the opcode) followed by the body.
inline unsigned short opcode_of(const void* pkt) { return pkt ? *(const unsigned short*)pkt : 0; }
inline const unsigned char* payload_of(const void* pkt) { return pkt ? (const unsigned char*)pkt + 2 : NULL; }

// ---- finding a handler -----------------------------------------------------------------------------

// A handler by name, with or without the class: "CPFsCharacter::fc_NC_CHARSAVE_ALL_REQ" or
// "fc_NC_CHARSAVE_ALL_REQ". The stored-procedure wrappers (CSQLP*::usp_*) are in the same table and can be
// looked up - and hooked - the same way.
inline void* handler_address(const char* name) {
    for (int i = 0; i < kHandlerCount; i++) {
        const char* h = kHandlers[i].name;
        if (detail::str_cmp(h, name) == 0) return rebase(kHandlers[i].va, kImageBase);
        const char* colon = h;
        for (const char* q = h; *q; q++) if (q[0] == ':' && q[1] == ':') colon = q + 2;
        if (colon != h && detail::str_cmp(colon, name) == 0) return rebase(kHandlers[i].va, kImageBase);
    }
    return NULL;
}

inline bool hook_handler(const char* name, void* replacement, Detour* out) {
    void* target = handler_address(name);
    if (!target) { log("[hook] NO SUCH HANDLER in character_symbols.h: %s", name); return false; }
    return hook_function(name, target, replacement, out);
}

}  // namespace chr

// ---- hooking a handler -----------------------------------------------------------------------------
//
// Inside the body you have:  self (the CPFs*), pkt (the NETPACKET*), a2 (the int argument - Account.pdb
// types it int and does not name it), and you RETURN the handler's int result. Handlers are __thiscall;
// the thunk turns ECX into an ordinary first parameter exactly as ZONE_HOOK_PACKET does.
//
// VARIADIC for the same reason as ZONE_HOOK_PACKET: braces do not protect commas from the preprocessor.
#define CHAR_HOOK_HANDLER(NAME, ...)                                                                   \
    static hook::Detour chr_detour_##NAME;                                                             \
    static int __fastcall chr_impl_##NAME(void* self, void* /*edx*/, void* pkt, int a2);                \
    static void __declspec(naked) chr_thunk_##NAME() {                                                 \
        __asm { jmp chr_impl_##NAME }                                                                  \
    }                                                                                                  \
    static int __fastcall chr_impl_##NAME(void* self, void* /*edx*/, void* pkt, int a2) __VA_ARGS__

// The original handler's result, from inside a body.
#define CHAR_CALL_ORIGINAL_OF(NAME)                                                                    \
    (((int(__fastcall*)(void*, void*, void*, int))chr_detour_##NAME.trampoline)(self, 0, pkt, a2))

#define CHAR_INSTALL_HANDLER(NAME)                                                                     \
    chr::hook_handler(#NAME, (void*)chr_thunk_##NAME, &chr_detour_##NAME)
