"""Generate zonehook's symbol table from Zone.pdb.

    python zone/tools/mk_symbols.py --pdb Z:/ServerSource/Zone00/Zone.pdb --exe Z:/ServerSource/Zone00/Zone.exe \
        --out include/zone_symbols.h

Every address the DLL hooks comes from here, never from a number typed into C++. The zone's packet handlers
are `ShinePlayer::sp_NC_<NAME>` - 195 of them - and they are NOT virtual (the mangling says QAE = public
__thiscall, not UAE), so they cannot be reached by swapping a vtable slot; each one is detoured where it
stands. The table also carries the handful of genuinely virtual classes, for the cases where a vtable swap
IS the right tool.

The header is generated, not hand-written, so a different Zone build is one command away rather than a
hunt for stale constants. It records the PDB's own GUID/age so the DLL can refuse to load against an exe it
was not built for.
"""
import argparse
import hashlib
import os
import re
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, 'C:/Projects/Fiesta2026on2016/tools')
import disasm_at as D  # noqa: E402

HANDLER = re.compile(r'^\?(sp_NC_[A-Z0-9_]+)@ShinePlayer@ShineObjectClass@@QAEXPATNETCOMMAND@@HG@Z$')

# Named anchors: hook points that are not packet handlers.
#
# The one that matters is where DEFERRED SET-UP goes. DllMain runs during loader init, before the exe's CRT,
# on a stack with very little committed - enough that a static-CRT DLL dies there (see src/nocrt.h). So
# DllMain should install one hook and nothing else, and the real work happens later.
#
# NOT WinMain: these exes are Windows services. WinMain runs, calls StartServiceCtrlDispatcher, and that
# BLOCKS - the SCM then calls the service's own routine on a different thread, and that is where the zone
# actually starts. Hooking WinMain would run our set-up in the wrong place and before the service exists.
#
# WinService::startDispatcher(String, bool(*)(), void(*)()) is the wrapper around
# StartServiceCtrlDispatcher; its two function pointers are the service's start and stop callbacks.
# ZoneServer::zs_ServiceThreadFunction is the zone's own service thread (SG = static __stdcall returning
# unsigned long, i.e. an LPTHREAD_START_ROUTINE) and is the natural "the zone is starting" anchor.
ANCHORS = {
    'ZoneServiceThread': '?zs_ServiceThreadFunction@ZoneServer@@SGKPAX@Z',
    'StartDispatcher': '?startDispatcher@WinService@@QAE_NVString@@P6A_NXZP6AXXZ@Z',
    'WinMain': '_WinMain@16',
    # Data, vtables and template functions are NOT anchors any more: mk_types.py generates a typed accessor
    # for every one - zone::global::chargedbuffdatabox(), zone::global::gpp(), zone::vtable::ItemInventory(),
    # zone::fn::SocketBundle_GameDBSession___sb_GetSocket() - from the global stream and the public names.
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--pdb', default='Z:/ServerSource/Zone00/Zone.pdb')
    ap.add_argument('--exe', default='Z:/ServerSource/Zone00/Zone.exe')
    ap.add_argument('--out', default=os.path.join(HERE, '..', 'include', 'zone_symbols.h'))
    a = ap.parse_args()

    secs = D.sections(a.exe)[0]   # sections() returns (list, ...); the list is what maps seg -> VA
    pdb = open(a.pdb, 'rb').read()
    base = 0x400000
    handlers, extra = {}, {}
    for name, seg, off in D.publics(pdb):
        if not (1 <= seg <= len(secs)):
            continue
        va = base + secs[seg - 1][0] + off
        m = HANDLER.match(name)
        if m:
            handlers[m.group(1)] = va
        elif name.startswith('??_7') and 'ShinePlayer' in name:
            extra.setdefault(name, va)

    anchors = {}
    want = {v: k for k, v in ANCHORS.items()}
    for name, seg, off in D.publics(pdb):
        if name in want and 1 <= seg <= len(secs):
            anchors[want[name]] = base + secs[seg - 1][0] + off

    exe_sha = hashlib.sha256(open(a.exe, 'rb').read()).hexdigest()
    out = [
        '// GENERATED by zone/tools/mk_symbols.py - do not edit.',
        '//   pdb %s' % os.path.basename(a.pdb),
        '//   exe %s  sha256 %s' % (os.path.basename(a.exe), exe_sha),
        '//',
        '// Addresses are absolute VAs for the default image base 0x%08X. The loader may relocate the image'
        % base,
        '// (the exe sets DYNAMIC_BASE), so every address is rebased at runtime against the real module base:',
        '// see zone::rebase() in hook.h. Never use one of these as a raw pointer.',
        '#pragma once',
        '// Self-contained: plain `unsigned int`, so this can be included before anything else.',
        '',
        'namespace zone {',
        '',
        'static const unsigned int kImageBase = 0x%08Xu;' % base,
        'static const char kExeSha256[] = "%s";' % exe_sha,
        '',
        '// ShinePlayer::sp_NC_<NAME>(TNETCOMMAND*, int, unsigned short) - the packet handlers.',
        '// void __thiscall, so a detour must preserve ECX (the ShinePlayer*).',
        'struct Handler { const char* name; unsigned int va; };',
        'static const Handler kHandlers[] = {',
    ]
    for name in sorted(handlers):
        out.append('    { "%s", 0x%08Xu },' % (name, handlers[name]))
    out += [
        '};',
        'static const int kHandlerCount = %d;' % len(handlers),
        '',
    ]
    out.append('// Anchors - see ANCHORS in mk_symbols.py for why the service thread, and not WinMain.')
    for k in sorted(anchors):
        out.append('static const unsigned int kVa%s = 0x%08Xu;' % (k, anchors[k]))
    out.append('')

    if extra:
        out.append('// vtables, for the cases where swapping a slot is the right tool')
        out.append('struct Vtable { const char* name; unsigned int va; };')
        out.append('static const Vtable kVtables[] = {')
        for name in sorted(extra):
            out.append('    { "%s", 0x%08Xu },' % (name.replace('"', ''), extra[name]))
        out += ['};', 'static const int kVtableCount = %d;' % len(extra), '']
    out.append('}  // namespace zone')

    dest = os.path.abspath(a.out)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    open(dest, 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
    print('%s: %d packet handlers, %d vtables' % (dest, len(handlers), len(extra)))


if __name__ == '__main__':
    main()
