"""Generates packet_guard_rules.h (zone C->S): per opcode the 2016 struct's fixed size (Zone.pdb, via the FiestaLib-Reloaded
extract) and, for a struct ending in a flexible array, its count field + element size.

    python gen_rules.py        (needs C:/Projects/ik-fiesta-bots/lib/FiestaLib-Reloaded beside this repo)

zone_handlers.txt: the ShinePlayer::sp_NC_* handler names of Zone.pdb
(ik-fiesta-bots tools/pdb_disasm.py --find '?sp_NC_'), i.e. the opcodes a client can send the zone.
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
M = 'C:/Projects/ik-fiesta-bots/lib/FiestaLib-Reloaded/docs/extracted/merged'
structs = json.load(open(M + '/all-structs.json', encoding='utf-8'))
ps, rt = structs['protocol_structs'], structs['referenced_types']
enums = json.load(open(M + '/all-enums.json', encoding='utf-8'))
opcode = {}
for dept, d in enums.items():
    if isinstance(d, dict) and 'opcodes' in d:
        for name, cmd in d['opcodes'].items():
            opcode[name] = (d['id'] << 10) | cmd
handlers = [l.strip() for l in open(os.path.join(HERE, 'zone_handlers.txt')) if l.strip()]

PRIM = {'unsigned char': 1, 'char': 1, 'unsigned short': 2, 'short': 2, 'unsigned long': 4, 'long': 4, 'int': 4,
        'unsigned int': 4, 'float': 4, 'unsigned __int64': 8, '__int64': 8}

# read from the handlers (pdb_disasm), where the struct extract has no usable count / element size:
#   BOOTH_OPEN: items at 31, count = byte 30 >> 1, BoothItem 12 bytes (sp_NC_BOOTH_OPEN_REQ 0x58EAB3 / add 0xC);
#   MINIHOUSE CREATE_FURNITURE / REARRANGE: count byte 0 (capped at 0x188), 7 bytes each (so_mh_* 0x544FBD / add 7)
OVERRIDE = {'NC_BOOTH_OPEN_REQ': (30, 1, 1, 12), 'NC_MINIHOUSE_CREATE_FURNITURE_REQ': (0, 1, 0, 7),
            'NC_MINIHOUSE_REARRANGE_REQ': (0, 1, 0, 7)}


def size_of(t):
    t = t.strip()
    m = re.match(r'^(.*)\[(\d+)\]$', t)
    if m:
        s = size_of(m.group(1))
        return None if s is None else s * int(m.group(2))
    if t in PRIM:
        return PRIM[t]
    for src in (ps, rt):
        if t in src and src[t].get('SizeOf') is not None:
            return src[t]['SizeOf']
    return None


rows, notes = [], []
for h in handlers:
    if h not in opcode:
        notes.append('no opcode: ' + h)
        continue
    s = ps.get('PROTO_' + h)
    if s is None:
        notes.append('no struct (empty body): ' + h)
        rows.append((opcode[h], h, 0, -1, 0, 0, 0))
        continue
    fields = s.get('fields', [])
    size = s['SizeOf']
    cnt_off, cnt_size, elem, shift = -1, 0, 0, 0
    if fields and re.search(r'\[0\]$', fields[-1]['type']):
        flex = fields[-1]
        es = size_of(flex['type'][:-3])
        prev = [f for f in fields[:-1] if f['type'] in ('unsigned char', 'unsigned short', 'unsigned long')]
        if prev and es:                        # the count: the last byte / word / dword before the array
            c = prev[-1]
            cnt_off, cnt_size, elem = c['offset'], PRIM[c['type']], es
        else:
            notes.append('flexible array without a usable count: %s (%s)' % (h, flex['type']))
    if h in OVERRIDE:
        cnt_off, cnt_size, shift, elem = OVERRIDE[h]
    rows.append((opcode[h], h, size, cnt_off, cnt_size, elem, shift))

rows.sort()
out = ['// GENERATED by gen_rules.py from FiestaLib-Reloaded docs/extracted (Zone.pdb structs + opcodes) - do not edit.',
       '// {opcode, fixed size of the 2016 struct (= where a trailing array starts), count field offset (-1 none), count size,',
       '//  count shift (the count is field >> shift), element size, name}',
       'struct Rule { unsigned short op; unsigned short size; short count_at; unsigned char count_size; unsigned char shift; '
       'unsigned short elem; const char* name; };',
       'static const Rule kRules[] = {']
for op, h, size, co, cs, e, sh in rows:
    out.append('    {0x%04X, %d, %d, %d, %d, %d, "%s"},' % (op, size, co, cs, sh, e, h))
out.append('};')
open(os.path.join(HERE, 'packet_guard_rules.h'), 'w', encoding='utf-8', newline='\r\n').write('\n'.join(out) + '\n')
print(len(rows), 'rules;', sum(1 for r in rows if r[3] >= 0), 'with a count')
print('\n'.join(notes))
