// packet_guard - the zone checks a client packet against its own length before the stock handler reads it
// (Fiesta2026on2016 P6 hardening, operator 2026-10-04: "fix potential crash bugs in the zone and client from malformed
// packets (e.g. length fields) or strings").
//
// The 2016 handlers trust the counts inside a packet. sp_NC_ACT_CHAT_REQ (0x45A400) hands byte 1 (len) and the text at
// +2 straight to the chat broadcast, sp_NC_BOOTH_OPEN_REQ (0x58E900) walks (byte 30 >> 1) 12-byte items from +31 and
// so_mh_CreateFurniture / so_mh_ReArrangeFurniture up to 392 7-byte records - none of them compares that against the
// packet's length. A packet that claims more than it carries makes the zone read past it (the receive buffer, then
// whatever lies beyond: garbage broadcast to the map, or a fault).
//
// RULES (packet_guard_rules.h, generated by gen_rules.py from the Zone.pdb structs, the hand-read ones noted there):
//   * a packet with a COUNT (a struct ending in a flexible array) must carry fixed part + count x element: anything
//     shorter is DROPPED (never reaches the handler) and logged. A legitimate packet always carries what its handler
//     reads, so no real client is affected.
//   * every other handled opcode: shorter than the 2016 struct is LOGGED only (a 2026 client may send a shorter form
//     the bridge or the handler copes with - observe first, then decide what to enforce).
// Each (opcode, rule) logs its first 20 hits, then every 1000th.
#include <zonehook.h>
#include <zone_functions.h>

#include <cstring>

namespace {

#include "packet_guard_rules.h"

const unsigned kVaProtocolStore = 0x004D4510u;   // protocolstore(PROTOCOLFUNCTIONTEMPLETE<ShinePlayer>*), cdecl
zone::Detour g_store;

short g_rule_of[0x10000];                        // opcode -> index into kRules, -1 none
short g_string_of[0x10000];                      // opcode -> first index into kStrings, -1 none
unsigned g_terminated[0x10000];
// a terminated copy lives in a per-thread ring: the zone keeps the last command pointer for a while (sp_LastProtocol)
thread_local unsigned char t_copy[4][0x2000];
thread_local int t_copy_next = 0;
unsigned g_dropped[0x10000], g_short[0x10000];

bool should_log(unsigned n) { return n <= 20 || n % 1000 == 0; }

unsigned char_no(void* player) {
    return player ? (unsigned)zone::fn::ShineObjectClass__ShinePlayer__so_GetCharRegistNumber()(player, 0) : 0;
}

void on_packet(hook::proto::Call& c) {
    const unsigned char* cmd = (const unsigned char*)c.args[0];
    const int n = (int)c.args[1] - 2;                // the length covers the opcode
    const int i = c.op < 0x10000 ? g_rule_of[c.op] : -1;
    if (i < 0 || !cmd) { c.original(); return; }
    const Rule& r = kRules[i];
    const unsigned char* p = cmd + 2;
    if (r.count_at >= 0) {
        long need = r.count_at + r.count_size;
        if (n >= need) {
            unsigned count = r.count_size == 1 ? p[r.count_at]
                           : r.count_size == 2 ? (unsigned)(p[r.count_at] | (p[r.count_at + 1] << 8))
                           : (unsigned)(p[r.count_at] | (p[r.count_at + 1] << 8) | (p[r.count_at + 2] << 16) | ((unsigned)p[r.count_at + 3] << 24));
            count >>= r.shift;
            need = (long)r.size + (long)count * r.elem;
        }
        if (n < need) {
            if (should_log(++g_dropped[c.op]))
                zone::log("packet_guard: DROPPED %s 0x%04X from char %u: %d byte(s), its count needs %ld (#%u)", r.name,
                          c.op, char_no(c.self), n, need, g_dropped[c.op]);
            return;                                  // swallowed: the handler never sees it (c.result stays 1)
        }
    } else if (n < (int)r.size) {
        if (should_log(++g_short[c.op]))
            zone::log("packet_guard: short %s 0x%04X from char %u: %d byte(s) < the 2016 struct's %u (passed on, #%u)",
                      r.name, c.op, char_no(c.self), n, r.size, g_short[c.op]);
    }
    // fixed string fields must end inside their field: a name / title / password with no NUL is read on into the
    // fields after it (or past the packet) by the zone's string copies. Terminated in a copy, never in the receive buffer.
    const int s0 = g_string_of[c.op];
    if (s0 >= 0 && n + 2 <= (int)sizeof t_copy[0]) {
        unsigned char* copy = 0;
        for (int s = s0; s < (int)(sizeof kStrings / sizeof kStrings[0]) && kStrings[s].op == c.op; s++) {
            const StringField& f = kStrings[s];
            if (n < f.at + f.size || memchr(p + f.at, 0, f.size)) continue;
            if (!copy) {
                copy = t_copy[t_copy_next++ & 3];
                memcpy(copy, cmd, n + 2);
                c.args[0] = (hook::u32)copy;
            }
            copy[2 + f.at + f.size - 1] = 0;
            if (should_log(++g_terminated[c.op]))
                zone::log("packet_guard: %s from char %u had no NUL in its %u bytes - terminated (#%u)", f.name,
                          char_no(c.self), f.size, g_terminated[c.op]);
        }
    }
    c.original();
}

void __cdecl store(void* table) {
    ((void(__cdecl*)(void*))g_store.trampoline)(table);
    if (table != zone::client_protocol_table()) return;
    int hooked = 0, counted = 0;
    for (int s = (int)(sizeof kStrings / sizeof kStrings[0]) - 1; s >= 0; s--) g_string_of[kStrings[s].op] = (short)s;
    for (int i = 0; i < (int)(sizeof kRules / sizeof kRules[0]); i++) {
        const Rule& r = kRules[i];
        if (r.size == 0 && r.count_at < 0) continue;             // nothing to check
        if (!hook::proto::is_registered(table, r.op)) continue;
        g_rule_of[r.op] = (short)i;
        if (hook::proto::hook_opcode<0>(table, r.op, on_packet, hook::proto::kPacketArg1)) {
            hooked++;
            if (r.count_at >= 0) counted++;
        }
    }
    zone::log("packet_guard: %d client request handler(s) checked, %d with a count (dropped when short), the rest logged",
              hooked, counted);
}

}  // namespace

ZONEHOOK_PLUGIN("packet_guard") {
    memset(g_rule_of, 0xFF, sizeof g_rule_of);
    memset(g_string_of, 0xFF, sizeof g_string_of);
    zone::hook_function("protocolstore(ShinePlayer table) 0x4D4510 (+ packet length checks)",
                        (void*)zone::rebase(kVaProtocolStore), (void*)store, &g_store);
}
