// GENERATED by client/addresses/client_sigs.py header - do not edit; edit symbols.json / builds/*.json and rerun.
// The 2026 client plugins' addresses per Fiesta.exe build (PE TimeDateStamp). caddr::va(caddr::kX) returns the
// address at the default image base (pass it to hook::rebase), or 0 when the running build is unknown or the
// symbol was not found in it - a plugin then logs and does not hook.
#pragma once
#include <windows.h>
#include <initializer_list>

namespace caddr {

enum Sym {
    kNpcDialogHandler,
    kQuestRecordLookup,
    kControlAttribute,
    kEnhanceWarnJump,
    kExpGainCtor,
    kExpGainHandler,
    kFormatExp64,
    kExpTotalObject,
    kFullMapAddQuestHelper,
    kSlideListGetItemData,
    kMobAreaMarkQuest,
    kMobAreaMarkMob,
    kQuestHelperMarkQuest,
    kQuestHelperMarkMob,
    kMapLegendHeading,
    kMapMarkLabelNumber,
    kMapMarkSite,
    kMapMarkLabelPath,
    kMapMarkLabelCont,
    kMapMarkAreasOnly,
    kMasteryRead,
    kMasteryReadBack,
    kMasteryFormat,
    kMasteryFormatBack,
    kMasteryFormatString,
    kMinimonPickupSite,
    kWindowPostMessage,
    kMinimonPickupAfter,
    kWinRegisterPos,
    kWinSetPos,
    kFwRegister,
    kFwRestore,
    kFwTerminate,
    kScreenW,
    kScreenH,
    kQuestFinishUpdate,
    kGetQuestMgr,
    kQuestGetStatus,
    kSaveWinPos,
    kSendNetMsg,
    kWinPosLoadA,
    kWinPosLoadB,
    kSkillLearnHandler,
    kActiveSkillTable,
    kQuickSlots,
    kQuickBarRedraw,
    kQuestListSkipA,
    kQuestListSkipB,
    kNiShutdown,
    kMapSingleton,
    kMapSingletonGuard,
    kMapSingletonDtor,
    kMapSingletonAtexit,
    kPgWinPostMsg,
    kPgWinProcessMsg,
    kWinMgrIsIn,
    kWinMgr,
    kRewardWinExpHighStore,
    kQuestHelperAddProgress,
    kQuestHelperRemoveProgress,
    kCount
};

inline const char* const kNames[kCount] = {
    "NpcDialogHandler",
    "QuestRecordLookup",
    "ControlAttribute",
    "EnhanceWarnJump",
    "ExpGainCtor",
    "ExpGainHandler",
    "FormatExp64",
    "ExpTotalObject",
    "FullMapAddQuestHelper",
    "SlideListGetItemData",
    "MobAreaMarkQuest",
    "MobAreaMarkMob",
    "QuestHelperMarkQuest",
    "QuestHelperMarkMob",
    "MapLegendHeading",
    "MapMarkLabelNumber",
    "MapMarkSite",
    "MapMarkLabelPath",
    "MapMarkLabelCont",
    "MapMarkAreasOnly",
    "MasteryRead",
    "MasteryReadBack",
    "MasteryFormat",
    "MasteryFormatBack",
    "MasteryFormatString",
    "MinimonPickupSite",
    "WindowPostMessage",
    "MinimonPickupAfter",
    "WinRegisterPos",
    "WinSetPos",
    "FwRegister",
    "FwRestore",
    "FwTerminate",
    "ScreenW",
    "ScreenH",
    "QuestFinishUpdate",
    "GetQuestMgr",
    "QuestGetStatus",
    "SaveWinPos",
    "SendNetMsg",
    "WinPosLoadA",
    "WinPosLoadB",
    "SkillLearnHandler",
    "ActiveSkillTable",
    "QuickSlots",
    "QuickBarRedraw",
    "QuestListSkipA",
    "QuestListSkipB",
    "NiShutdown",
    "MapSingleton",
    "MapSingletonGuard",
    "MapSingletonDtor",
    "MapSingletonAtexit",
    "PgWinPostMsg",
    "PgWinProcessMsg",
    "WinMgrIsIn",
    "WinMgr",
    "RewardWinExpHighStore",
    "QuestHelperAddProgress",
    "QuestHelperRemoveProgress",
};

struct Build {
    unsigned stamp;
    const char* version;
    unsigned va[kCount];
};

inline const Build kBuilds[] = {
    {0x6AA04F02u, "10.6.4", {0x007275C0, 0x005C5550, 0x0097FAD0, 0x00646A41, 0x0073F050, 0x0073F0E0, 0x00796200, 0x00C1BB08, 0x00610610, 0x005255C0, 0x00663EA0, 0x00663EB0, 0x00664190, 0x006641A0, 0x0061180C, 0x0061089A, 0x0061076E, 0x00610782, 0x00610788, 0x00610959, 0x00690D16, 0x00690D20, 0x00690D5A, 0x00690D5F, 0x00B31E68, 0x00586678, 0x00874AE0, 0x005866A7, 0x007D8A60, 0x007D8C30, 0x00569F70, 0x0056A2D0, 0x0056F4F0, 0x00C321C0, 0x00C321C4, 0x00730250, 0x007EB840, 0x008FF590, 0x00571B70, 0x00890B00, 0x0055E330, 0x0055FCC0, 0x005AD110, 0x00CE4F30, 0x00C1750C, 0x0057E2D0, 0x007363AD, 0x0073927C, 0x009D71B0, 0x00C54E00, 0x00CE1E40, 0x007A51F0, 0x00AEAF90, 0x00877A40, 0x008784C0, 0x00881DA0, 0x00D1B810, 0x00697E0D, 0x007EC640, 0x007EC800}},
    {0x6AB41A55u, "10.6.6", {0x00727BF0, 0x005C5A50, 0x00980260, 0x00646F91, 0x0073F6A0, 0x0073F730, 0x00796810, 0x00C1CB08, 0x00610B90, 0x00525760, 0x006643D0, 0x006643E0, 0x006646C0, 0x006646D0, 0x00611D8C, 0x00610E1A, 0x00610CEE, 0x00610D02, 0x00610D08, 0x00610ED9, 0x006912E6, 0x006912F0, 0x0069132A, 0x0069132F, 0x00B32F54, 0x00586AA8, 0x00875230, 0x00586AD7, 0x007D91C0, 0x007D9390, 0x0056A390, 0x0056A6F0, 0x0056F910, 0x00C331C0, 0x00C331C4, 0x00730890, 0x007EBFC0, 0x008FFD20, 0x00571F90, 0x00891250, 0x0055E750, 0x005600E0, 0x005AD630, 0x00CE5F30, 0x00C1850C, 0x0057E6F0, 0x007369ED, 0x007398BC, 0x009D7910, 0x00C55E00, 0x00CE2E40, 0x007A5850, 0x00AEB700, 0x00878190, 0x00878C10, 0x008824F0, 0x00D1C810, 0x006983DD, 0x007ECDC0, 0x007ECF80}},
};

inline const Build* current() {
    static const Build* cur = nullptr;
    static bool done = false;
    if (!done) {
        done = true;
        const unsigned char* m = (const unsigned char*)GetModuleHandleA(nullptr);
        const IMAGE_NT_HEADERS* nt = (const IMAGE_NT_HEADERS*)(m + ((const IMAGE_DOS_HEADER*)m)->e_lfanew);
        for (const Build& b : kBuilds)
            if (b.stamp == nt->FileHeader.TimeDateStamp) cur = &b;
    }
    return cur;
}

inline unsigned va(Sym s) {
    const Build* b = current();
    return b ? b->va[s] : 0;
}

// the first of `need` this build lacks (its name), or nullptr when the plugin can hook - "unknown build" when the
// running Fiesta.exe is none of kBuilds
inline const char* missing(std::initializer_list<Sym> need) {
    if (!current()) return "unknown Fiesta.exe build (run client/addresses/client_sigs.py resolve)";
    for (Sym s : need)
        if (!va(s)) return kNames[s];
    return nullptr;
}

}  // namespace caddr
